#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "docopt"
require "in_that_case"
require "in_that_case/cli"

OPTION_ALIGN_WIDTH = 15
CLI = InThatCase::CLI.new(InThatCase::CONVENTIONS, OPTION_ALIGN_WIDTH)

doc = <<DOC
In That Case

Usage:
  itc #{CLI.convention_option_list} [<input>]
  itc -h | --help

Arguments:
  <input>        The input text to be converted, if empty stdin will be used.

Options:
#{CLI.option_documentation}
DOC

begin
  args  = Docopt::docopt(doc)
  input = args.fetch("<input>")
  input = $stdin.gets.chomp if input.nil?

  puts InThatCase.convert(input, CLI.to_convention(args))
rescue Docopt::Exit, InThatCase::InThatCaseError => e
  warn e.message
  exit 1
end
